# Generated by Django 3.1.6 on 2021-02-27 03:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('name_2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Test_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_id', models.DateTimeField(default=datetime.datetime(2021, 2, 27, 3, 19, 53, 13618, tzinfo=utc))),
            ],
        ),
    ]
