# Generated by Django 3.1.6 on 2021-02-27 04:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0004_auto_20210227_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_list',
            name='created_id',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 27, 4, 6, 36, 696560, tzinfo=utc)),
        ),
    ]
