# Generated by Django 3.1.6 on 2021-02-27 04:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0005_auto_20210227_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_list',
            name='created_id',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 27, 4, 10, 1, 659079, tzinfo=utc)),
        ),
    ]
