# Generated by Django 3.1.6 on 2021-02-27 04:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0007_auto_20210227_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trello_app.test_list'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test_list',
            name='created_id',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 27, 4, 15, 24, 175588, tzinfo=utc)),
        ),
    ]
