# Generated by Django 3.1.6 on 2021-02-27 04:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0008_auto_20210227_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_list',
            name='created_id',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 27, 4, 16, 14, 561849, tzinfo=utc)),
        ),
    ]
