# Generated by Django 3.1.6 on 2021-03-07 04:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0009_auto_20210227_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 4, 55, 18, 349839, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='test_list',
            name='created_id',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 4, 55, 18, 290821, tzinfo=utc)),
        ),
    ]
