# Generated by Django 3.1.6 on 2021-03-07 05:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trello_app', '0010_auto_20210307_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_list',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 5, 3, 25, 893370, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='test_list',
            name='created_id',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 5, 3, 25, 893370, tzinfo=utc)),
        ),
    ]
